BRANDS = [
    {
        "name": "Cookies",
        "base_url": "https://shop.cookies.co",
        "thca_url": "https://shop.cookies.co/collections/thca",
        "brightfield_rank": 1,
        "brightfield_funnel_pct": 30.6,
    },
    {
        "name": "Cheech and Chong",
        "base_url": "https://shopcheechandchong.com",
        "thca_url": "https://shopcheechandchong.com/collections/thca-flower",
        "brightfield_rank": 2,
        "brightfield_funnel_pct": 29.7,
    },
    {
        "name": "iDelta",
        "base_url": "https://delta8vapeoil.com",
        "thca_url": "https://delta8vapeoil.com/product-category/thca/",
        "brightfield_rank": 4,
        "brightfield_funnel_pct": 25.6,
    },
    {
        "name": "Mood",
        "base_url": "https://mood.com",
        "thca_url": "https://mood.com/collections/thca",
        "brightfield_rank": 6,
        "brightfield_funnel_pct": 18.6,
    },
    {
        "name": "Mellow Fellow",
        "base_url": "https://mellowfellow.fun",
        "thca_url": "https://mellowfellow.fun/collections/thca",
        "brightfield_rank": 7,
        "brightfield_funnel_pct": 16.9,
    },
    {
        "name": "Mystic Labs",
        "base_url": "https://mysticlabsd8.com",
        "thca_url": "https://mysticlabsd8.com/thca/",
        "brightfield_rank": 9,
        "brightfield_funnel_pct": 16.1,
    },
    {
        "name": "Delta Munchies",
        "base_url": "https://deltamunchies.com",
        "thca_url": "https://deltamunchies.com/collections/thca-products",
        "brightfield_rank": 10,
        "brightfield_funnel_pct": 14.9,
    },
    {
        "name": "STIIIZY Hemp",
        "base_url": "https://www.stiiizy.com",
        "thca_url": "https://www.stiiizy.com/collections/thca",
        "brightfield_rank": 11,
        "brightfield_funnel_pct": 14.3,
    },
    {
        "name": "Hempbombs",
        "base_url": "https://www.hempbombs.com",
        "thca_url": "https://www.hempbombs.com/thca/",
        "brightfield_rank": 12,
        "brightfield_funnel_pct": 14.1,
    },
    {
        "name": "CBDistillery",
        "base_url": "https://www.cbdistillery.com",
        "thca_url": "https://www.cbdistillery.com/collections/thca",
        "brightfield_rank": 13,
        "brightfield_funnel_pct": 13.5,
    },
    {
        "name": "incredibles",
        "base_url": "https://iloveincredibles.com",
        "thca_url": "https://iloveincredibles.com/collections/thca",
        "brightfield_rank": 14,
        "brightfield_funnel_pct": 13.2,
    },
    {
        "name": "HoneyRoot",
        "base_url": "https://honeyrootwellness.com",
        "thca_url": "https://honeyrootwellness.com/collections/thca",
        "brightfield_rank": 15,
        "brightfield_funnel_pct": 12.7,
    },
    {
        "name": "Koi CBD",
        "base_url": "https://koicbd.com",
        "thca_url": "https://koicbd.com/thca/",
        "brightfield_rank": 16,
        "brightfield_funnel_pct": 12.7,
    },
    {
        "name": "Moonwlkr",
        "base_url": "https://moonwlkr.com",
        "thca_url": "https://moonwlkr.com/collections/thca",
        "brightfield_rank": 17,
        "brightfield_funnel_pct": 12.4,
    },
    {
        "name": "Space Gods",
        "base_url": "https://shopspacegods.com",
        "thca_url": "https://shopspacegods.com/collections/thca",
        "brightfield_rank": 18,
        "brightfield_funnel_pct": 12.1,
    },
    {
        "name": "enjoy",
        "base_url": "https://enjoyhemp.co",
        "thca_url": "https://enjoyhemp.co/shop-by-category/thca/",
        "brightfield_rank": 19,
        "brightfield_funnel_pct": 11.5,
    },
    {
        "name": "Torch",
        "base_url": "https://torchhemp.com",
        "thca_url": "https://torchhemp.com/collections/thc-a",
        "brightfield_rank": 20,
        "brightfield_funnel_pct": 11.4,
    },
    {
        "name": "TRE House",
        "base_url": "https://trehouse.com",
        "thca_url": "https://trehouse.com/collections/thca-products",
        "brightfield_rank": 21,
        "brightfield_funnel_pct": 11.4,
    },
    {
        "name": "Exhale",
        "base_url": "https://www.exhalewell.com",
        "thca_url": "https://www.exhalewell.com/thca/",
        "brightfield_rank": 22,
        "brightfield_funnel_pct": 11.3,
    },
    {
        "name": "ELYXR",
        "base_url": "https://www.elyxr.com",
        "thca_url": "https://www.elyxr.com/collections/thca-products/",
        "brightfield_rank": 23,
        "brightfield_funnel_pct": 11.0,
    },
]

TEST_LOCATIONS = [
    {"state": "Ohio", "abbreviation": "OH", "zip_code": "43215", "city": "Columbus"},
    {"state": "Texas", "abbreviation": "TX", "zip_code": "78701", "city": "Austin"},
]

SHIPPING_POLICY_PATHS = [
    "/policies/shipping-policy",
    "/pages/shipping-policy",
    "/pages/shipping",
    "/shipping-policy",
    "/shipping",
    "/pages/faq",
    "/faq",
    "/pages/help",
]

STATE_RESTRICTION_KEYWORDS = [
    "ohio", "texas", "OH", "TX",
    "restricted state", "restricted states",
    "do not ship", "does not ship", "cannot ship",
    "unable to ship", "not available in",
    "prohibited state", "prohibited states",
    "excluded state", "excluded states",
    "we don't ship", "we do not deliver",
    "not eligible for shipping",
    "shipping restrictions",
]
